from . import views

from django.conf import settings
from django.urls import path
from django.conf.urls.static import static

urlpatterns = [
    path('login', views.login_view),
    path('register', views.registration_view),
    path('logout', views.logout_view),
    path('csrf', views.csrf_view),
    path('products', views.products),
    path('products/<category>', views.products),
    path('product/add', views.add_product),
    path('product/<int:product_id>/view', views.view_product),
    path('product/<int:product_id>/edit', views.edit_product),
    path('productcategories', views.product_categories),
    path('getUser', views.getUser),
    path('getPerms', views.getPerms),
    path('resources', views.resources),
    path('resource_orders', views.resource_orders),
    path('allergens', views.allergens),
    path('cars', views.cars),
    path('cars_view', views.cars_view),
    path('cars_view/<int:car_id>', views.cars_view),
    path('my_orders/<int:user_id>', views.my_orders),
    path('my_orders_view', views.my_orders_view),
    path('my_orders_view/<int:order_id>', views.my_orders_view),
    path('my_orders_cancel/<int:order_id>', views.my_orders_cancel),
    path('my_orders_pay/<int:order_id>', views.my_orders_pay),
    path('my_orders_accept/<int:order_id>', views.my_orders_accept),
    path('my_orders_reject/<int:order_id>', views.my_orders_reject),
    path('my_orders_complete/<int:order_id>', views.my_orders_complete),
    path('resource_order', views.resource_order),
    path('resource_order/<int:order_id>', views.resource_order_detail),
    path('resource_orders_history', views.resource_orders_history),
    path('resource_view', views.resource_view),
    path('resource_view/<int:resource_id>', views.resource_view),
    path('resourceOrderChangeState/<int:resource_id>/<str:state>', views.resourceOrderChangeState),
    path('resourceOrderDelivered/<int:resource_id>', views.resourceOrderDelivered),
    path('user_view', views.user_view),
    path('user_view/<int:user_id>', views.user_view),
    path('user_create_view', views.user_create_view),
    path('users', views.users),
    path('users/drivers', views.drivers),
    path('groups', views.groups),
    path('orders', views.orders),
    path('orders/<int:order_id>', views.order_detail),
    path('orders/<int:order_id>/setstate/<str:state>', views.order_set_state),
    path('product_order', views.product_order),
    path('states', views.states),
    path('orders/<int:order_id>/products', views.products_by_order),
    path('routes', views.routes_view),
    path('routes/<int:route_id>', views.route_view),
    path('routes/add', views.route_view),
    path('product/<int:product_id>/allergens', views.product_allergens),
    path('orders_plan/<date>', views.orders_plan),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
